library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
data=read.csv("F:/suthaRstudio/gender.csv")
tree <-rpart(Height~Gender+Weight,data)
a <-data.frame(Gender=c("female"),Weight=c(76))
result <-predict(tree,a)
print(result)
rpart.plot(tree)
tree <-rpart(Gender~Height+Weight,data)
a <-data.frame(Height=c(149),Weight=c(75))
result <-predict(tree,a)
print(result)
rpart.plot(tree)
